global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: linker-metrics

rule_files: 
-  /etc/prometheus/prometheus.rules

scrape_configs:
- job_name: prometheus
  scrape_interval: 5s
  scrape_timeout: 4s 

  static_configs:
    # These endpoints are scraped via HTTP.
    - targets: ['192.168.10.71:10000','192.168.10.70:10000']
